apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: log-test
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output.conf

  output.conf: |
    [OUTPUT]
        Name            azure
        Match           *cust-*
        Customer_ID     ${WorkspaceId}
        Shared_Key      ${SharedKey}
        Log_Type        ${LogName}

  input-kubernetes.conf: |
    [INPUT]
        Name              tail 
        Path              /var/log/cust-type1.log
        Tag               cust-kyc
        Parser            json-logs

    [INPUT]
        Name              tail 
        Path              /var/log/cust-type2.log
        Tag               cust-crq
        Parser            json-logs
    [INPUT]
        Name              tail 
        Path              /var/log/cust-type3.log
        Tag               cust-karte
        Parser            json-logs
        
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Trim      On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On

    [FILTER]
        Name          nest
        Match         kube.*
        Operation     lift
        Nested_under  kubernetes
        Add_prefix    kubernetes_

    [FILTER]
        Name          nest
        Match         kube.*
        Operation     lift
        Nested_under  kubernetes_labels
        Add_prefix    kubernetes_labels_

    [FILTER]
        Name lua
        Match cust-kyc
        script mappings.lua
        call map_fields_kyc
    [FILTER]
        Name lua
        Match cust-crq
        script mappings.lua
        call map_fields_crq
    [FILTER]
        Name lua
        Match cust-karte
        script mappings.lua
        call map_fields_karte

  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    time
        Time_Format %d/%b/%Y:%H:%M:%S %z
        Time_Keep   Off
    [PARSER]
        Name        json-logs
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S %z
    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S

    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep Off

  mappings.lua: |
     function map_fields_kyc (tag, timestamp, record)
        new_record = {}
        new_record["log_tag"] = tag
        new_record["log_thread"] = record["thread_name"]
        new_record["log_level"] = record["level"]
        new_record["log_logger"] = record["logger_name"]
        new_record["log_message"] = record["message"]
        new_record["log_original"] = record
        
        return 1, timestamp, new_record 
      end

      function map_fields_crq (tag, timestamp, record)
        new_record = {}
        new_record["log_tag"] = tag
        new_record["log_thread"] = record["Thread"]
        new_record["log_level"] = record["Severity"]
        new_record["log_logger"] = record["LoggerName"]
        new_record["log_message"] = record["message"]
        new_record["log-original"] = record
        
        return 1, timestamp, new_record 
      end

      function map_fields_karte (tag, timestamp, record)
        new_record = {}
        new_record["log_tag"] = tag
        new_record["log_thread"] = record["threadName"]
        new_record["log_level"] = record["level"]
        new_record["log_logger"] = record["loggerName"]
        new_record["log_message"] = record["message"]
        new_record["log_original"] = record
        
        return 1, timestamp, new_record 
      end
