apiVersion: v1
kind: Pod
metadata:
  name: logapp-type1
  labels:
    app: logapp-type1

spec:
  restartPolicy: Never
  containers:
  - name: logtype1
    imagePullPolicy: Always
    image: maxjahn/dummylog:type1
