apiVersion: v1
kind: Pod
metadata:
  name: logapp-type1
  namespace: log-test
  labels:
    app: logapp-type1

spec:
  restartPolicy: Never
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  priorityClassName: system-node-critical
  serviceAccountName: fluent-bit
  terminationGracePeriodSeconds: 10
  containers:
  - name: logtype1
    imagePullPolicy: Always
    image: maxjahn/dummylog:type1

    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers


  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers

