apiVersion: v1
kind: Pod
metadata:
  name: logapp-type2
  labels:
    app: logapp-type2

spec:
  restartPolicy: Never
  containers:
  - name: logtype2
    imagePullPolicy: Always
    image: maxjahn/dummylog:type2
